### ISSUE TITLE
Error when using Nuxt3.

### ISSUE THREAD

**Issue by onpix** [kidonng/unocss-preset-daisy#10]
I have the same problem as [#6 ]; that is, when using Nuxt3 + UnoCSS + daisyUI preset, styles are incorrect in `nuxi preview`, but everything works well when in `nuxi dev`.

I also make a small online demo to reproduce this problem:

[https://stackblitz.com/edit/nuxt-starter-5h7iuh](https://stackblitz.com/edit/nuxt-starter-5h7iuh)

and a StackOverflow question for more details:

[https://stackoverflow.com/questions/74576221/how-to-correctly-use-unocss-presets-with-nuxt3](https://stackoverflow.com/questions/74576221/how-to-correctly-use-unocss-presets-with-nuxt3)

**Comment by onpix** [comment]
In UnoCSS inspector, I found other presets work well and their rules are matched but the rules of this daisyUI preset are "Potentially Unmatched". For example:

```
Potentially Unmatched
avatar, badge, badge-base, badge-primary
```

**Comment by hermesalvesbr** [comment]
Did you get it resolved?

**Comment by onpix** [comment]
> Did you get it resolved?

No... I tried for some days and finally switched back to the vanilla tailwindCSS.

**Comment by Rednas83** [comment]
I can't get it even to work with `nuxi dev`.

**nuxt.config.ts**
```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
import { transformerDirectives } from 'unocss'
import presetDaisy from 'unocss-preset-daisy'

export default defineNuxtConfig({
  extends: 'content-wind',
  modules: ['@unocss/nuxt'],
  css: ['@unocss/reset/tailwind.css', '~/style.css'],
  unocss: {
    // presets
    uno: true, // enabled `@unocss/preset-uno`
    icons: true, // enabled `@unocss/preset-icons`
    attributify: true, // enabled `@unocss/preset-attributify`,
    presets: [presetDaisy()],

    // core options
    shortcuts: [],
    transformers: [transformerDirectives()],
    rules: [],
  }
})
```
**plugins/ono-ui.ts**
```
import OnuUI from 'onu-ui'
// import '@unocss/reset/tailwind.css' /* daisyUI assumes Tailwind CSS's Preflight */
import '@kidonng/daisyui/index.css' /* Import daisyUI **BEFORE** UnoCSS */
import 'uno.css'
import 'onu-ui/dist/style.css'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(OnuUI)
})
```
**Resulting in:**
![image](https://user-images.githubusercontent.com/25219229/215475787-a8cd13d0-75c7-4444-b666-7817b26f6965.png)

Any advice?

**Comment by meixger** [comment]
Seems to be a issue how UnoCss + cssnano interact.
Styles are working as expected after disabling `cssnano` in `nuxt.config.ts`.

![image](https://user-images.githubusercontent.com/600424/220286842-e5321563-5bef-475b-983b-15679cc6dcdb.png)

https://stackblitz.com/edit/github-gxjzue-1jzxtn?file=nuxt.config.ts

ref: https://github.com/nuxt/nuxt/issues/19177

**Comment by meixger** [comment]
Related https://github.com/kidonng/unocss-preset-daisy/issues/6

**Comment by kidonng** [comment]
Please open a new issue if you still experience it with latest depedencies.
