### ISSUE TITLE
Error when using nuxt3

### ISSUE THREAD

**Issue by Rednas83** [kidonng/unocss-preset-daisy#11]
With the just released version there is an error when used with nuxt3
![image](https://user-images.githubusercontent.com/25219229/222703566-1dc64497-c651-45c7-aa84-cb8a6aff1481.png)

Is it missing a default value?

**Comment by kidonng** [comment]
This package now uses named export, please [see the release notes](https://github.com/kidonng/unocss-preset-daisy/releases/tag/v2.0.0):

```diff
- import presetDaisy from 'unocss-preset-daisy'
+ import {presetDaisy} from 'unocss-preset-daisy'
```
