### ISSUE TITLE
Cannot find daisyui colors

### ISSUE THREAD

**Issue by Rednas83** [kidonng/unocss-preset-daisy#15]
With the latest v2.51.3 there is now an error after following the installation instructions for Nuxt
`Cannot find module 'daisyui/src/colors/index.js'`

**Comment by kidonng** [comment]
I cannot reproduce with a fresh Nuxt 3 setup. Please ensure you have followed the readme closely (which just got a minor revision). Also:

- Which version of `nuxt`, `unocss` and `unocss-preset-daisy` are you using?
- Which package manager are you using?
