### ISSUE TITLE
unmet peer unocss@^0.50.3: found 0.51.5

### ISSUE THREAD

**Issue by J4gQBqqR** [kidonng/unocss-preset-daisy#21]
Unocss has upgraded to 0.51.5. However, this preset is still requiring 0.50.3

Release number is: 4.0.0

![图片](https://user-images.githubusercontent.com/77554817/233514472-8f8d799a-f5e5-40d2-a701-94182d8bdf9c.png)

**Comment by ryuheechul** [comment]
looks like changing the semver requirement to `^0.50` would fix the warning.

**Comment by kidonng** [comment]
See https://github.com/kidonng/unocss-preset-daisy/issues/28#issuecomment-1706182049
