### ISSUE TITLE
unmet peer unocss@^0.53.1: found 0.55.0

### ISSUE THREAD

**Issue by Aspire1Inspire2** [kidonng/unocss-preset-daisy#28]
![图片](https://github.com/kidonng/unocss-preset-daisy/assets/12798470/272e5446-a7be-4c58-a43c-adad293d79ba)

Unocss has upgraded to 0.55.0. However, this preset is still requiring 0.53.1

Release number is: 6.0.0

related issue: #21 

Hi Developer,
Could you help relieve the requirement of package dependencies? Currently, the package dependency is too strict. Uno updates version number frequently. But this preset does not update that frequently, thus the dependent Uno release is constantly outdated.

**Comment by kidonng** [comment]
Thanks for reporting! Actually this package does not depend on UnoCSS at runtime, you can ignore the warning/work around the dependency requirement if you have issues.

That said, this has been fixed in [v6.0.1](https://github.com/kidonng/unocss-preset-daisy/releases/tag/v6.0.1).
