### ISSUE TITLE
Nuxt typescript error

### ISSUE THREAD

**Issue by Rednas83** [kidonng/unocss-preset-daisy#34]
With Nuxt I get a typescript error in the nuxt.config file after exactly following the installation instructions. The package manager that was used is pnpm

Tried:
* Updating to the latest packages
* Restarting vscode

**nuxt.config.ts**
![image](https://github.com/kidonng/unocss-preset-daisy/assets/25219229/2586280b-a696-4c66-90f2-b3db8c083791)
**package.json**
```
    "nuxt": "^3.8.0",
    "@kidonng/daisyui": "2.51.3",
    "@unocss/reset": "^0.57.2",
    "daisyui": "^3.9.4",
    "unocss": "^0.57.2",
    "unocss-preset-daisy": "^7.0.0",
```

**Comment by kidonng** [comment]
Cannot reproduce. Make sure your dependencies are up to date without version mismatch.

Also, [`@kidonng/daisyui` has been unnecessary since v3](https://github.com/kidonng/unocss-preset-daisy/releases/tag/v3.0.0).

**Comment by Rednas83** [comment]
Uninstalled @kidonng/daisyui but still no daisyui styles.

**Tried:**
`<div class="alert-success">alert-success</div>` 
returns 
![image](https://github.com/kidonng/unocss-preset-daisy/assets/25219229/43dd6d4d-e91f-4922-b358-fb0e7a4cc199)

**Tried:**
`<div class="alert alert-success">alert-success</div>` 
returns 
![image](https://github.com/kidonng/unocss-preset-daisy/assets/25219229/7de6bf6a-1691-4e99-ae4f-149593fd53d4)

**Tried:**
```
`<div class="r-2">alert-success</div>`
.r-2 {
  @apply border;
  @apply border-black;
  @apply alert-success;
  @apply text-center;
}
```
returns
![image](https://github.com/kidonng/unocss-preset-daisy/assets/25219229/2061fb4b-d985-4031-a606-b1acfe0835f6)

Is there a working playground for nuxt? It did work in the past but at some point not anymore😕
