### ISSUE TITLE
Nuxt 3 issue

### ISSUE THREAD

**Issue by lightglitch** [kidonng/unocss-preset-daisy#4]
Hi,

I'm trying to use this preset with nuxt 3 but the css `@kidonng/daisyui/index.css` is not included anywhere.
I don't see how to include this manually in the project the way you use in your demo.

Any help on solving this? Thx

**Comment by lightglitch** [comment]
Solved it

**Comment by kidonng** [comment]
It would be better if you provided more details and especially how you solved it, so you can help others having similiar problem.

**Comment by lightglitch** [comment]
It was simple, just adding the import in the css property on the nuxt configuration.
