### ISSUE TITLE
Getting error "Must use import to load ES Module"

### ISSUE THREAD

**Issue by subhasish-smiles** [kidonng/unocss-preset-daisy#7]
Getting this error while trying it with solid js, vite and unocss. 

```
[ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/hp/myWorkspace/solid-capacitor/client/node_modules/unocss-preset-daisy/index.js
require() of ES modules is not supported.
```

**Comment by Dustella** [comment]
Since node will not run esm directly, you should add `"type": "module"` in your `package.json`.

**Comment by kidonng** [comment]
Please try the latest version if you are still encountering issues.

This is a good read on (pure) ESM package: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
