### ISSUE TITLE
Couldn't find a way to define which theme I want to use

### ISSUE THREAD

**Issue by philippedasilva-orizone** [kidonng/unocss-preset-daisy#8]
Hi,

I'm trying to see if daisyui could be my ui kit for my current project but I couldn't figure out what I should do to define a theme I want to use.

I see some direct imports on the @kidonng/daisyui documentation but it doesn't state where they should go.

Could you please give me some insights or redirect me to the documentation I missed specifying exactly how I should do it? :)

Thanks

**Comment by kidonng** [comment]
Sorry for the late reply.

> I see some direct imports on the @kidonng/daisyui documentation but it doesn't state where they should go.

Well, they go where you would import CSS normally. The docs are using CSS `@import` but with most bundlers you can import them in JS as well:

```js
// main.js
import './your-style.css'
import '@kidonng/daisyui/themes/<theme-name>.css'
import 'uno.css'
```

Then specify the theme in the markup:

```html
<body data-theme="cupcake"></body>
```

If your question is regarding custom themes, please see https://github.com/kidonng/unocss-preset-daisy/issues/9#issuecomment-1452292840.
